train_task_id: [MinAtar/Asterix, MinAtar/Breakout, MinAtar/Freeway, MinAtar/SpaceInvaders]
test_task_id: [MinAtar/Asterix, MinAtar/Breakout, MinAtar/Freeway, MinAtar/SpaceInvaders]

source_path: task_src/OffPolicyRL

change_q_update: false
change_policy: false
change_networks: false
change_optim: false
change_rb: false
change_train: false
change_activation: false
