train_task_id: [SMAX/2s3z, SMAX/3s5z, SMAX/3s_vs_5z, SMAX/3s5z_vs_3s6z, SMAX/5m_vs_6m, SMAX/10m_vs_11m, SMAX/27m_vs_30m, SMAX/6h_vs_8z, SMAX/smacv2_5_units, SMAX/smacv2_10_units, SMAX/smacv2_20_units]
test_task_id: []

source_path: task_src/OnPolicyMARL
template_backend: recurrent

change_config: false
change_optim: false
change_loss: false
change_networks: false
change_train: false
