blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://alexgoldie.github.io/discobench/
    about: Check the documentation before opening an issue
  - name: Discussions
    url: https://github.com/AlexGoldie/discobench/discussions
    about: Ask questions and discuss ideas with the community
